Selesai: Latihan menangani error dengan try-except
TypeError: Occurs when you try to perform an operation on an unsupported type.
Example: 5 + "apel" (menjumlahkan angka dan teks).

FileNotFoundError: Terjadi saat Anda mencoba membuka file yang tidak ada.
Example: with open("file_yang_tidak_ada.txt", "r") as file:.

IndexError: Occurs when you try to access an index in a list that is out of range.
Example: my_list = [1, 2, 3], lalu Anda memanggil my_list[5].

KeyError: The dictionary equivalent of IndexError; occurs when you try to access a key that doesn't exist.
Example: my_dict = {"nama": "Budi"}, lalu Anda memanggil my_dict["umur"].